#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAMS.MediaLib.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WAMS.DB")]
	public partial class MediaAssetsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMediaAsset(MediaAsset instance);
    partial void UpdateMediaAsset(MediaAsset instance);
    partial void DeleteMediaAsset(MediaAsset instance);
    #endregion
		
		public MediaAssetsDataContext() : 
				base(global::WAMS.MediaLib.Properties.Settings.Default.WAMS_DBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MediaAssetsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaAssetsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaAssetsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MediaAssetsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MediaAsset> MediaAssets
		{
			get
			{
				return this.GetTable<MediaAsset>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MediaAssets")]
	public partial class MediaAsset : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private string _Title;
		
		private System.DateTime _Created;
		
		private string _Encoding;
		
		private System.DateTime _ExpireOn;
		
		private string _OriginalFile;
		
		private string _ProcessingTime;
		
		private string _Protection;
		
		private string _Renderer;
		
		private System.Nullable<int> _Size;
		
		private string _Thumbnail;
		
		private string _Url;
		
		private string _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnCreatedChanging(System.DateTime value);
    partial void OnCreatedChanged();
    partial void OnEncodingChanging(string value);
    partial void OnEncodingChanged();
    partial void OnExpireOnChanging(System.DateTime value);
    partial void OnExpireOnChanged();
    partial void OnOriginalFileChanging(string value);
    partial void OnOriginalFileChanged();
    partial void OnProcessingTimeChanging(string value);
    partial void OnProcessingTimeChanged();
    partial void OnProtectionChanging(string value);
    partial void OnProtectionChanged();
    partial void OnRendererChanging(string value);
    partial void OnRendererChanged();
    partial void OnSizeChanging(System.Nullable<int> value);
    partial void OnSizeChanged();
    partial void OnThumbnailChanging(string value);
    partial void OnThumbnailChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
		
		public MediaAsset()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Created", DbType="DateTime NOT NULL")]
		public System.DateTime Created
		{
			get
			{
				return this._Created;
			}
			set
			{
				if ((this._Created != value))
				{
					this.OnCreatedChanging(value);
					this.SendPropertyChanging();
					this._Created = value;
					this.SendPropertyChanged("Created");
					this.OnCreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Encoding", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Encoding
		{
			get
			{
				return this._Encoding;
			}
			set
			{
				if ((this._Encoding != value))
				{
					this.OnEncodingChanging(value);
					this.SendPropertyChanging();
					this._Encoding = value;
					this.SendPropertyChanged("Encoding");
					this.OnEncodingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpireOn", DbType="DateTime NOT NULL")]
		public System.DateTime ExpireOn
		{
			get
			{
				return this._ExpireOn;
			}
			set
			{
				if ((this._ExpireOn != value))
				{
					this.OnExpireOnChanging(value);
					this.SendPropertyChanging();
					this._ExpireOn = value;
					this.SendPropertyChanged("ExpireOn");
					this.OnExpireOnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OriginalFile", DbType="NVarChar(100)")]
		public string OriginalFile
		{
			get
			{
				return this._OriginalFile;
			}
			set
			{
				if ((this._OriginalFile != value))
				{
					this.OnOriginalFileChanging(value);
					this.SendPropertyChanging();
					this._OriginalFile = value;
					this.SendPropertyChanged("OriginalFile");
					this.OnOriginalFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessingTime", DbType="NChar(8)")]
		public string ProcessingTime
		{
			get
			{
				return this._ProcessingTime;
			}
			set
			{
				if ((this._ProcessingTime != value))
				{
					this.OnProcessingTimeChanging(value);
					this.SendPropertyChanging();
					this._ProcessingTime = value;
					this.SendPropertyChanged("ProcessingTime");
					this.OnProcessingTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Protection", DbType="NVarChar(100)")]
		public string Protection
		{
			get
			{
				return this._Protection;
			}
			set
			{
				if ((this._Protection != value))
				{
					this.OnProtectionChanging(value);
					this.SendPropertyChanging();
					this._Protection = value;
					this.SendPropertyChanged("Protection");
					this.OnProtectionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Renderer", DbType="NVarChar(256)")]
		public string Renderer
		{
			get
			{
				return this._Renderer;
			}
			set
			{
				if ((this._Renderer != value))
				{
					this.OnRendererChanging(value);
					this.SendPropertyChanging();
					this._Renderer = value;
					this.SendPropertyChanged("Renderer");
					this.OnRendererChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="Int")]
		public System.Nullable<int> Size
		{
			get
			{
				return this._Size;
			}
			set
			{
				if ((this._Size != value))
				{
					this.OnSizeChanging(value);
					this.SendPropertyChanging();
					this._Size = value;
					this.SendPropertyChanged("Size");
					this.OnSizeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thumbnail", DbType="NVarChar(MAX)")]
		public string Thumbnail
		{
			get
			{
				return this._Thumbnail;
			}
			set
			{
				if ((this._Thumbnail != value))
				{
					this.OnThumbnailChanging(value);
					this.SendPropertyChanging();
					this._Thumbnail = value;
					this.SendPropertyChanged("Thumbnail");
					this.OnThumbnailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(MAX)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(50)")]
		public string Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
