//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WAMSDemo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WAMSDemo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets are being ingested into Media Services container. Please, wait..
        /// </summary>
        internal static string AssetUploading {
            get {
                return ResourceManager.GetString("AssetUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding process has failed. Please try again later..
        /// </summary>
        internal static string FailedToEncode {
            get {
                return ResourceManager.GetString("FailedToEncode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File could not be uploaded because {0}..
        /// </summary>
        internal static string FailedToUploadFileMessage {
            get {
                return ResourceManager.GetString("FailedToUploadFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File of size {0} has been uploaded successfully in {1} seconds..
        /// </summary>
        internal static string FileUploadedMessage {
            get {
                return ResourceManager.GetString("FileUploadedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding job has finished successfully..
        /// </summary>
        internal static string JobFinished {
            get {
                return ResourceManager.GetString("JobFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding job is being processed....
        /// </summary>
        internal static string JobInProcess {
            get {
                return ResourceManager.GetString("JobInProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding job has been queued for processing..
        /// </summary>
        internal static string JobScheduled {
            get {
                return ResourceManager.GetString("JobScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding job has started successfully..
        /// </summary>
        internal static string JobStarted {
            get {
                return ResourceManager.GetString("JobStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding job has been submitted successfully..
        /// </summary>
        internal static string JobSubmitted {
            get {
                return ResourceManager.GetString("JobSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Media Service is not initialized. Refresh the screen and try again later.&lt;/strong&gt;.
        /// </summary>
        internal static string MediaNotInitialized {
            get {
                return ResourceManager.GetString("MediaNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current session has expired. Please reload the Home page again..
        /// </summary>
        internal static string SessonExpired {
            get {
                return ResourceManager.GetString("SessonExpired", resourceCulture);
            }
        }
    }
}
